"""
app.py

Gradio interface for FitFindr with multi-step interactive planning loop.

The planning loop follows the workflow described in planning.md:
1. User enters query → search_listings
2. Results shown → user chooses: "Get outfit" or "Search again"
3. If outfit selected → suggest_outfit
4. User chooses: "Get Instagram caption" or "Search again"
5. If caption selected → create_fit_card
6. User chooses: "Continue shopping" or "Done"

Run with:
    python app.py

Then open the localhost URL shown in your terminal (usually http://localhost:7860).
"""

import gradio as gr

from agent import run_agent, _parse_query
from tools import search_listings, suggest_outfit, create_fit_card
from utils.data_loader import get_example_wardrobe, get_empty_wardrobe


# ── state management ──────────────────────────────────────────────────────────

class InteractionState:
    """Tracks the state of a multi-step interaction."""

    def __init__(self):
        self.step = "search"  # search, results, outfit, caption, done
        self.session = {}
        self.wardrobe = None


# ── step 1: search ────────────────────────────────────────────────────────────

def handle_search(user_query: str, wardrobe_choice: str, state: InteractionState) -> tuple:
    """
    Step 1: User enters a query and we search for listings.

    Returns:
        (listing_output, outfit_output, fit_card_output,
         status_message, show_outfit_btn, show_search_again_btn)
    """
    # Guard against empty query
    if not user_query or not user_query.strip():
        return "", "", "", "❌ Please enter a search query.", False, False

    # Select wardrobe
    if wardrobe_choice == "Example wardrobe":
        wardrobe = get_example_wardrobe()
    else:
        wardrobe = get_empty_wardrobe()

    # Run the agent (which calls search_listings, selects top item)
    session = run_agent(user_query, wardrobe)
    state.session = session
    state.wardrobe = wardrobe

    # If search failed, stay at search step
    if session["error"]:
        return "", "", "", f"❌ {session['error']}", False, False

    # Search succeeded, move to results step
    state.step = "results"
    listing_text = _format_listing(session["selected_item"])

    return (
        listing_text, "", "",
        "✅ Found a match! Would you like to get outfit suggestions?",
        True,   # show_outfit_btn
        True,   # show_search_again_btn
    )


# ── step 2: get outfit ────────────────────────────────────────────────────────

def handle_get_outfit(state: InteractionState) -> tuple:
    """
    Step 2: User requested outfit suggestions.

    The outfit has already been generated by run_agent,
    so we just display it and update the UI.
    """
    if not state.session or not state.session["selected_item"]:
        return "", "", "", "❌ No item selected. Please search first.", False, False, False

    # The outfit_suggestion was already generated by run_agent
    outfit_text = state.session["outfit_suggestion"]
    state.step = "outfit"

    return (
        _format_listing(state.session["selected_item"]),
        outfit_text, "",
        "✅ Here's your outfit suggestion! Would you like an Instagram caption?",
        False,  # hide_outfit_btn
        True,   # show_caption_btn
        True,   # show_search_again_btn
    )


# ── step 3: get caption ───────────────────────────────────────────────────────

def handle_get_caption(state: InteractionState) -> tuple:
    """
    Step 3: User requested an Instagram caption (fit card).

    The caption has already been generated by run_agent,
    so we just display it and update the UI.
    """
    if not state.session or not state.session["selected_item"]:
        return "", "", "", "❌ No item selected. Please search first.", False, False, False

    # The fit_card was already generated by run_agent
    caption_text = state.session["fit_card"]
    state.step = "caption"

    return (
        _format_listing(state.session["selected_item"]),
        state.session["outfit_suggestion"],
        caption_text,
        "✨ Here's your fit card! Would you like to continue shopping?",
        False,  # hide_outfit_btn
        False,  # hide_caption_btn
        True,   # show_search_again_btn (relabeled as "Search again")
    )


# ── step 4: continue shopping ─────────────────────────────────────────────────

def handle_continue_shopping(state: InteractionState) -> tuple:
    """
    Step 4: Reset state and go back to search.
    """
    state.step = "search"
    state.session = {}

    return (
        "", "", "",
        "🔄 Ready for a new search! What would you like to find?",
        False,  # hide_outfit_btn
        False,  # hide_caption_btn
        False,  # hide_search_again_btn
    )


# ── formatting ────────────────────────────────────────────────────────────────

def _format_listing(item: dict) -> str:
    """
    Format a listing dict into a readable text representation for the UI.

    Args:
        item: A listing dict from search_listings().

    Returns:
        A formatted string with item details.
    """
    lines = []

    # Title/name
    title = item.get("title") or item.get("name") or "Item"
    lines.append(f"📦 {title}")

    # Price
    price = item.get("price")
    if price is not None:
        try:
            price_str = f"${float(price):.2f}"
            lines.append(f"💰 Price: {price_str}")
        except Exception:
            lines.append(f"💰 Price: {price}")

    # Platform
    platform = item.get("platform")
    if platform:
        lines.append(f"🌐 Platform: {platform}")

    # Size
    size = item.get("size")
    if size:
        lines.append(f"📏 Size: {size}")

    # Condition
    condition = item.get("condition")
    if condition:
        lines.append(f"✨ Condition: {condition}")

    # Category
    category = item.get("category")
    if category:
        lines.append(f"👕 Category: {category}")

    # Description
    description = item.get("description")
    if description:
        lines.append(f"\n📝 Description:\n{description}")

    # Colors
    colors = item.get("colors")
    if colors and isinstance(colors, list):
        lines.append(f"🎨 Colors: {', '.join([str(c) for c in colors if c])}")

    # Style tags
    style_tags = item.get("style_tags")
    if style_tags and isinstance(style_tags, list):
        lines.append(f"🏷️ Style: {', '.join([str(s) for s in style_tags if s])}")

    # Brand
    brand = item.get("brand")
    if brand:
        lines.append(f"👔 Brand: {brand}")

    return "\n".join(lines)


# ── interface ─────────────────────────────────────────────────────────────────

EXAMPLE_QUERIES = [
    "vintage graphic tee under $30",
    "90s track jacket in size M",
    "flowy midi skirt under $40",
    "black combat boots size 8",
    "designer ballgown size XXS under $5",   # deliberate no-results test
]


def build_interface():
    """Build the Gradio interface with multi-step planning loop."""

    with gr.Blocks(title="FitFindr") as demo:
        gr.Markdown("""
# FitFindr 🛍️
Find secondhand pieces and get outfit ideas based on your wardrobe.
Describe what you're looking for — include size and price if you want to filter.
        """)

        # State management
        state = gr.State(InteractionState())

        with gr.Row():
            query_input = gr.Textbox(
                label="What are you looking for?",
                placeholder="e.g. vintage graphic tee under $30, size M",
                lines=2,
                scale=3,
            )
            wardrobe_choice = gr.Radio(
                choices=["Example wardrobe", "Empty wardrobe (new user)"],
                value="Example wardrobe",
                label="Wardrobe",
                scale=1,
            )

        search_btn = gr.Button("🔍 Search", variant="primary")

        with gr.Row():
            listing_output = gr.Textbox(
                label="🛍️ Top listing found",
                lines=8,
                interactive=False,
            )
            outfit_output = gr.Textbox(
                label="👗 Outfit idea",
                lines=8,
                interactive=False,
            )
            fitcard_output = gr.Textbox(
                label="✨ Your fit card",
                lines=8,
                interactive=False,
            )

        # Status message
        status_msg = gr.Markdown("🔍 Ready to search! What would you like to find?")

        # Interactive buttons
        with gr.Row():
            outfit_btn = gr.Button("👗 Get outfit suggestion", visible=False, variant="secondary")
            caption_btn = gr.Button("✨ Get Instagram caption", visible=False, variant="secondary")
            search_again_btn = gr.Button("🔄 Search again", visible=False, variant="secondary")

        gr.Examples(
            examples=[[q, "Example wardrobe"] for q in EXAMPLE_QUERIES],
            inputs=[query_input, wardrobe_choice],
            label="Try these queries",
        )

        # Event handlers
        def search_click(query, wardrobe_choice, state):
            listing, outfit, caption, status, show_outfit, show_search = handle_search(
                query, wardrobe_choice, state
            )
            return {
                listing_output: listing,
                outfit_output: outfit,
                fitcard_output: caption,
                status_msg: status,
                outfit_btn: gr.update(visible=show_outfit),
                search_again_btn: gr.update(visible=show_search),
                state: state,
            }

        def outfit_click(state):
            listing, outfit, caption, status, _, show_caption, show_search = handle_get_outfit(state)
            return {
                listing_output: listing,
                outfit_output: outfit,
                fitcard_output: caption,
                status_msg: status,
                outfit_btn: gr.update(visible=False),
                caption_btn: gr.update(visible=show_caption),
                search_again_btn: gr.update(visible=show_search),
                state: state,
            }

        def caption_click(state):
            listing, outfit, caption, status, _, _, show_search = handle_get_caption(state)
            return {
                listing_output: listing,
                outfit_output: outfit,
                fitcard_output: caption,
                status_msg: status,
                caption_btn: gr.update(visible=False),
                search_again_btn: gr.update(visible=show_search),
                state: state,
            }

        def search_again_click(state):
            _, _, _, status, _, _, _ = handle_continue_shopping(state)
            return {
                listing_output: gr.update(value=""),
                outfit_output: gr.update(value=""),
                fitcard_output: gr.update(value=""),
                status_msg: status,
                outfit_btn: gr.update(visible=False),
                caption_btn: gr.update(visible=False),
                search_again_btn: gr.update(visible=False),
                query_input: gr.update(value=""),
                state: state,
            }

        # Connect button clicks to handlers
        search_btn.click(
            fn=search_click,
            inputs=[query_input, wardrobe_choice, state],
            outputs=[listing_output, outfit_output, fitcard_output, status_msg, outfit_btn, search_again_btn, state],
        )

        outfit_btn.click(
            fn=outfit_click,
            inputs=[state],
            outputs=[listing_output, outfit_output, fitcard_output, status_msg, outfit_btn, caption_btn, search_again_btn, state],
        )

        caption_btn.click(
            fn=caption_click,
            inputs=[state],
            outputs=[listing_output, outfit_output, fitcard_output, status_msg, caption_btn, search_again_btn, state],
        )

        search_again_btn.click(
            fn=search_again_click,
            inputs=[state],
            outputs=[listing_output, outfit_output, fitcard_output, status_msg, outfit_btn, caption_btn, search_again_btn, query_input, state],
        )

        # Allow Enter key to trigger search
        query_input.submit(
            fn=search_click,
            inputs=[query_input, wardrobe_choice, state],
            outputs=[listing_output, outfit_output, fitcard_output, status_msg, outfit_btn, search_again_btn, state],
        )

    return demo


if __name__ == "__main__":
    demo = build_interface()
    demo.launch()
